---
# defaults file for proxmox_vm_build
ansible_ssh_common_args: "-o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no"
PROXMOX_HOST: "192.168.0.200"
PROXMOX_USER: "svcansadmin@pam"
PROXMOX_PASSWORD: ""
PROXMOX_TOKEN_ID: "AnsibleAccess"
PROXMOX_TOKEN_SECRET: "c06e73d2-1075-415a-9fdc-0f2c292ee328"
PROXMOX_NODE: "pve"