---
- name: Get OS Family
  ansible.builtin.setup:
    gather_subset:
      - 'os_family'
  delegate_to: "{{ VM_NAME }}"
  register: os_info
  become: yes
  tags: configure

- name: Set hostname inside the VM
  hostname:
    name: "{{ VM_NAME }}"
  delegate_to: "{{ VM_NAME }}"
  become: yes
  tags: configure

# - name: Assign static IP inside the VM
#   ansible.builtin.template:
#     src: static_ip_config.j2
#     dest: /etc/sysconfig/network-scripts/ifcfg-{{ vm_interfaces}}
#   delegate_to: "{{ VM_NAME }}"
#   become: yes
#   tags: configure

- name: Assign static IP inside the VM 
  community.general.nmcli:
    conn_name: "{{ vm_interfaces}}"
    ifname: "{{ vm_interfaces}}"
    type: ethernet
    autoconnect: yes
    ip4: "{{ VM_IP }}/{{ SUFFIX }}"
    gw4: "{{ VM_GW }}"
    dns4: 
      - "{{ VM_DNS1 }}"
      - "{{ VM_DNS2 }}"
      - "{{ VM_DNS3 }}"
    state: present
  delegate_to: "{{ VM_NAME }}"
  become: yes
  tags: configure

- name: Restart Network to apply static IP
  ansible.builtin.service:
    name: NetworkManager
    state: restarted
  delegate_to: "{{ VM_NAME }}"
  become: yes
  ignore_errors: yes
  tags: configure