[http]
  auth-enabled = true
  oidc-enabled = true
  oidc-client-id = "influxdb"
  oidc-client-secret = "influx-client-secret"
  oidc-issuer = "http://localhost:8080/auth/realms/sanjay-lab"
  oidc-redirect-url = "http://localhost:8086/oauth/callback"
  oidc-scopes = "openid,profile,email,roles"
  oidc-claim = "email"